### ISSUE TITLE
下载过程中取消下载

### ISSUE THREAD

**Issue by geekerliu** [shelwee/UpdateHelper#3]
下载过程中取消下载，第二次app启动后因为检测到文件已经存在，所以不会重新下载。
导致安装时提示pkg不完整，不能正常安装。

**Comment by shelwee** [comment]
已经修改了，在安装前检查APK完整性。

**Comment by lijunhuayc** [comment]
@geekerliu 请关注 https://github.com/lijunhuayc/EasyAndroidUpgrade
支持多线程断点续传，支持暂停，AS，
上线后应该会满足你的需求。
